//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1Console.ServiceReferenceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWCF.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PrimeNumber", ReplyAction="http://tempuri.org/IService/PrimeNumberResponse")]
        string PrimeNumber(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PrimeNumber", ReplyAction="http://tempuri.org/IService/PrimeNumberResponse")]
        System.Threading.Tasks.Task<string> PrimeNumberAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SumOfDigits", ReplyAction="http://tempuri.org/IService/SumOfDigitsResponse")]
        int SumOfDigits(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SumOfDigits", ReplyAction="http://tempuri.org/IService/SumOfDigitsResponse")]
        System.Threading.Tasks.Task<int> SumOfDigitsAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ReverseString", ReplyAction="http://tempuri.org/IService/ReverseStringResponse")]
        string ReverseString(string inputString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ReverseString", ReplyAction="http://tempuri.org/IService/ReverseStringResponse")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string inputString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PrintHtmlTags", ReplyAction="http://tempuri.org/IService/PrintHtmlTagsResponse")]
        string PrintHtmlTags(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PrintHtmlTags", ReplyAction="http://tempuri.org/IService/PrintHtmlTagsResponse")]
        System.Threading.Tasks.Task<string> PrintHtmlTagsAsync(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SortNumbers", ReplyAction="http://tempuri.org/IService/SortNumbersResponse")]
        int[] SortNumbers(string type, int[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SortNumbers", ReplyAction="http://tempuri.org/IService/SortNumbersResponse")]
        System.Threading.Tasks.Task<int[]> SortNumbersAsync(string type, int[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Assignment1Console.ServiceReferenceWCF.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Assignment1Console.ServiceReferenceWCF.IService>, Assignment1Console.ServiceReferenceWCF.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PrimeNumber(int num) {
            return base.Channel.PrimeNumber(num);
        }
        
        public System.Threading.Tasks.Task<string> PrimeNumberAsync(int num) {
            return base.Channel.PrimeNumberAsync(num);
        }
        
        public int SumOfDigits(int num) {
            return base.Channel.SumOfDigits(num);
        }
        
        public System.Threading.Tasks.Task<int> SumOfDigitsAsync(int num) {
            return base.Channel.SumOfDigitsAsync(num);
        }
        
        public string ReverseString(string inputString) {
            return base.Channel.ReverseString(inputString);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string inputString) {
            return base.Channel.ReverseStringAsync(inputString);
        }
        
        public string PrintHtmlTags(string tag, string data) {
            return base.Channel.PrintHtmlTags(tag, data);
        }
        
        public System.Threading.Tasks.Task<string> PrintHtmlTagsAsync(string tag, string data) {
            return base.Channel.PrintHtmlTagsAsync(tag, data);
        }
        
        public int[] SortNumbers(string type, int[] data) {
            return base.Channel.SortNumbers(type, data);
        }
        
        public System.Threading.Tasks.Task<int[]> SortNumbersAsync(string type, int[] data) {
            return base.Channel.SortNumbersAsync(type, data);
        }
    }
}
